apiVersion: apps/v1
kind: Deployment
metadata:
  name: executingdeploy
  labels:
    app: executingapp
spec:
  selector:
    matchLabels:
      app: executingapp
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: executingapp
    spec:
      containers:
      - name: executingapp
        image: 03021994/executing:latest
        command: ["python", "./app/executing.py"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"