FROM python:latest
RUN  mkdir -p /app
COPY ./src/BLANKET-prediction.csv ./
COPY ./src/TEMP-sensor.csv ./
COPY ./src/TEMPERATURE-limit.csv ./
COPY ./src/settings.yaml ./
COPY ./src/ /app/
RUN pip install -r ./app/requirement.txt
EXPOSE 5000
CMD [ "python", "./app/planning.py" ]